#!/usr/bin/env bash
#
# Grant warden-agent the ability to deploy Warden without a human in the loop.
#
#   sudo ~/warden/deploy/grant-deploy.sh
#
# Run this ONCE. After it, the agent can stage a new tree, install, migrate,
# build and restart on its own.
#
# ── What this actually grants, stated plainly ───────────────────────────────
#
# It installs a root-owned deploy script at /usr/local/sbin/warden-deploy that
# warden-agent may run with sudo. That script runs `npm ci` and `next build` as
# the `warden` user.
#
# npm lifecycle scripts execute arbitrary code. So in practice this grants:
#       warden-agent  ->  code execution as `warden`
# and `warden` must be able to read /opt/gam7/oauth2service.json, because that
# is the credential the application exists to use.
#
# Therefore: the earlier "denied: GAM credential" entry is no longer a real
# boundary. Anyone holding this key can reach domain-wide delegation by way of
# the app user. That is inherent to letting an agent deploy this app at all,
# not something a cleverer sudoers file fixes.
#
# It is a reasonable trade only when the workstation holding the agent's key
# already holds equivalent access (for example its own GAM credential with the
# same domain-wide delegation), so the marginal exposure is small. On a
# workstation that does NOT, this is a poor trade — deploy by hand instead.
#
# What it still does NOT grant: an interactive root shell, user management, or
# the ability to rewrite its own sudoers entry.
#
# Revoke:
#   sudo rm /etc/sudoers.d/warden-agent-deploy /usr/local/sbin/warden-deploy

set -euo pipefail

AGENT_USER="warden-agent"
APP_USER="warden"
APP_DIR="/opt/warden"
STAGE_DIR="/home/${AGENT_USER}/staging"

log()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mXX \033[0m %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "run as root (sudo $0)"
id -u "$AGENT_USER" >/dev/null 2>&1 || die "run deploy/agent-access.sh first"

log "creating staging directory ${STAGE_DIR}"
install -d -o "$AGENT_USER" -g "$AGENT_USER" -m 0755 "$STAGE_DIR"

# ── the deploy script ───────────────────────────────────────────────────────
# Root-owned and NOT writable by warden-agent — otherwise the agent could edit
# it and hand itself a root shell, which would make the whole exercise theatre.
log "installing /usr/local/sbin/warden-deploy"
cat >/usr/local/sbin/warden-deploy <<'DEPLOY'
#!/usr/bin/env bash
# Deploy Warden from the agent staging directory. Root-owned; see grant-deploy.sh.
set -euo pipefail

APP_USER="warden"
APP_DIR="/opt/warden"
STAGE_DIR="/home/warden-agent/staging"

log() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }

[[ -f "$STAGE_DIR/package.json" ]] || { echo "nothing staged in $STAGE_DIR"; exit 1; }

log "syncing staged tree into ${APP_DIR}"
install -d -o "$APP_USER" -g "$APP_USER" -m 0755 "$APP_DIR"
tar -C "$STAGE_DIR" --exclude node_modules --exclude .next --exclude .git -cf - . \
  | tar -C "$APP_DIR" -xf -
chown -R "$APP_USER:$APP_USER" "$APP_DIR"
# .env is generated by install.sh and must survive a redeploy.
chmod 0600 "$APP_DIR/.env" 2>/dev/null || true

# Dev deps are build-time inputs (tailwindcss, postcss, autoprefixer).
# Install everything, build, then prune.
log "installing dependencies"
if [[ -f "$APP_DIR/package-lock.json" ]]; then
  sudo -u "$APP_USER" -H bash -lc "cd '$APP_DIR' && npm ci --no-audit --no-fund"
else
  sudo -u "$APP_USER" -H bash -lc "cd '$APP_DIR' && npm install --no-audit --no-fund"
fi

log "prisma generate"
sudo -u "$APP_USER" -H bash -lc "cd '$APP_DIR' && npx prisma generate"

log "applying schema"
if compgen -G "$APP_DIR/prisma/migrations/*/migration.sql" >/dev/null; then
  sudo -u "$APP_USER" -H bash -lc "cd '$APP_DIR' && npx prisma migrate deploy"
else
  sudo -u "$APP_USER" -H bash -lc "cd '$APP_DIR' && npx prisma db push --skip-generate"
fi

log "building"
sudo -u "$APP_USER" -H bash -lc "cd '$APP_DIR' && npm run build"

log "pruning dev dependencies"
sudo -u "$APP_USER" -H bash -lc "cd '$APP_DIR' && npm prune --omit=dev --no-audit --no-fund" || true

log "syncing nginx site"
# Rendered from the installer's answers in /etc/warden/install.conf, so a redeploy carries
# template fixes without anyone re-typing the port or networks. Hosts installed before
# install.conf existed keep their hand-made config untouched.
if [[ -f /etc/warden/install.conf && -x "$APP_DIR/deploy/render-nginx.sh" ]]; then
  bash "$APP_DIR/deploy/render-nginx.sh" || log "  nginx render failed — previous config kept"
else
  log "  no /etc/warden/install.conf — nginx left as it is"
fi

log "restarting service"
systemctl restart warden-web 2>/dev/null || log "warden-web not installed yet"
systemctl is-active warden-web 2>/dev/null || true

log "deploy complete"
DEPLOY
chown root:root /usr/local/sbin/warden-deploy
chmod 0755 /usr/local/sbin/warden-deploy

# ── sudoers ─────────────────────────────────────────────────────────────────
log "granting ${AGENT_USER} -> warden-deploy"
cat >/etc/sudoers.d/warden-agent-deploy <<EOF
# Deploy rights for the Warden agent. See deploy/grant-deploy.sh for the
# honest description of what this grants (code execution as ${APP_USER}).
${AGENT_USER} ALL=(root) NOPASSWD: /usr/local/sbin/warden-deploy
${AGENT_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl daemon-reload
${AGENT_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl enable warden-loginscan.timer
${AGENT_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl restart warden-loginscan.timer
${AGENT_USER} ALL=(root) NOPASSWD: /usr/bin/install -m 0644 /home/${AGENT_USER}/staging/deploy/warden-web.service /etc/systemd/system/warden-web.service
${AGENT_USER} ALL=(root) NOPASSWD: /usr/bin/install -m 0644 /home/${AGENT_USER}/staging/deploy/warden-loginscan.service /etc/systemd/system/warden-loginscan.service
${AGENT_USER} ALL=(root) NOPASSWD: /usr/bin/install -m 0644 /home/${AGENT_USER}/staging/deploy/warden-loginscan.timer /etc/systemd/system/warden-loginscan.timer
${AGENT_USER} ALL=(root) NOPASSWD: /bin/bash /home/${AGENT_USER}/staging/deploy/setup-tls.sh *
${AGENT_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl reload nginx
EOF
chmod 0440 /etc/sudoers.d/warden-agent-deploy
visudo -cf /etc/sudoers.d/warden-agent-deploy >/dev/null || {
  rm -f /etc/sudoers.d/warden-agent-deploy
  die "sudoers validation failed — nothing installed"
}

# ── the destructive gate, moved somewhere the agent cannot write ───────────
# WARDEN_ALLOW_DESTRUCTIVE previously lived in /opt/warden/.env, which is owned by
# the warden user — and the agent can execute code as warden. That made the gate
# decorative. A root-owned systemd drop-in overrides EnvironmentFile, so enabling
# district-wide mail deletion now genuinely requires root.
log "installing root-owned destructive-ops gate"
GATE_DIR=/etc/systemd/system/warden-web.service.d
GATE_FILE="$GATE_DIR/10-destructive.conf"
install -d -m 0755 "$GATE_DIR"
if [[ ! -f "$GATE_FILE" ]]; then
  {
    printf '%s
' '# Sweeps are REFUSED unless this is exactly "1".'
    printf '%s
' '# Root-owned on purpose: the deploy agent can write /opt/warden/.env,'
    printf '%s
' '# so the gate cannot live there. After editing, run:'
    printf '%s
' '#   systemctl daemon-reload && systemctl restart warden-web'
    printf '%s
' '[Service]'
    printf '%s
' 'Environment=WARDEN_ALLOW_DESTRUCTIVE=0'
  } > "$GATE_FILE"
  chmod 0644 "$GATE_FILE"
  systemctl daemon-reload
  log "  gate at $GATE_FILE (currently 0 — sweeps refused)"
else
  log "  gate already present — left unchanged"
fi

# Firewall: the installer's deploy/ufw-warden.sh owns it, using /etc/warden/install.conf.

cat <<EOF

$(log "deploy rights granted")

  The agent can now:  scp a tree to ${STAGE_DIR}
                      sudo warden-deploy
                      sudo systemctl restart warden-web

  It still cannot:    open a root shell, manage users, rewrite its own sudoers

  Revoke:
    sudo rm /etc/sudoers.d/warden-agent-deploy /usr/local/sbin/warden-deploy

EOF
